# Generated by Django 3.2.7 on 2021-10-05 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='good_conduct',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='id_back',
        ),
        migrations.RemoveField(
            model_name='seeker',
            name='id_front',
        ),
    ]
