# Generated by Django 3.2.7 on 2021-10-06 18:33

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20211006_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to=profiles.models.user_documents_path),
        ),
        migrations.AddField(
            model_name='personal',
            name='good_conduct',
            field=models.FileField(blank=True, null=True, upload_to=profiles.models.user_documents_path),
        ),
        migrations.AddField(
            model_name='personal',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.user_id_path),
        ),
        migrations.AddField(
            model_name='personal',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.user_id_path),
        ),
        migrations.AddField(
            model_name='personal',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile/profile.png', null=True, upload_to=profiles.models.user_profile_path),
        ),
    ]
