# Generated by Django 3.2.7 on 2021-10-07 03:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
