# Generated by Django 3.2.7 on 2021-10-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20211003_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, default='job_images/jobs.jpg', null=True, upload_to='jobs/job_images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='jobs/job_videos/'),
        ),
    ]
